$font = JetBrainsMono Nerd Font

general {
    hide_cursor = false
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = ~/Pictures/wallpapers/wall.png
    blur_passes = 1
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 2
    inner_color = rgba(0, 0, 0, 0.0)
    outer_color = rgba(ffffffff) rgba(e5e5e5ee) 45deg
    check_color = rgba(fafafaff) rgba(d0d0d0ee) 120deg
    fail_color = rgba(edededff) rgba(a8a8a8ee) 40deg
    font_color = rgb(200, 200, 200)
    fade_on_empty = false
    rounding = 15
    font_family = $font
    placeholder_text =
    fail_text = $PAMFAIL
    dots_size = 0.2
    dots_spacing = 0.3
    position = 0, 0
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    font_size = 70
    font_family = Iosevka Nerd Font
    position = 0, -130
    halign = center
    valign = top
}

label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y"
    font_size = 16
    font_family = $font
    position = 0, -250
    halign = center
    valign = top
}
